version: '3.8'

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - GPT_API_KEY=${GPT_API_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    depends_on:
      - back
    networks:
      - app-network

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - .env

    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge